import React, { useState, useEffect } from 'react';
import {
  GitBranch,
  GitCommit,
  GitPullRequest,
  FolderGit2,
  Lock,
  Globe,
  CheckCircle2,
  AlertCircle,
  Copy,
  ExternalLink,
  RefreshCw,
  Terminal,
  ArrowLeft,
  ArrowRight,
  Sparkles,
  FileCode,
  FileText,
  Layers,
  KeyRound,
  Eye,
  EyeOff,
  Check,
  Zap,
  CheckCheck,
  ShieldCheck,
  ChevronRight
} from 'lucide-react';

interface SavedProject {
  id: string;
  name: string;
  code: string;
  updatedAt: number;
}

export default function GitHubPushHub() {
  const [projects, setProjects] = useState<SavedProject[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState<string>('');
  const [selectedProject, setSelectedProject] = useState<SavedProject | null>(null);

  // GitHub Settings
  const [githubPat, setGithubPat] = useState<string>('');
  const [showPat, setShowPat] = useState<boolean>(false);
  const [repoMode, setRepoMode] = useState<'new' | 'existing'>('new');
  const [repoName, setRepoName] = useState<string>('');
  const [repoDesc, setRepoDesc] = useState<string>('');
  const [isPrivate, setIsPrivate] = useState<boolean>(false);
  const [branch, setBranch] = useState<string>('main');
  const [commitMessage, setCommitMessage] = useState<string>('feat: initial autonomous build via satusitE Studio');

  // Push Process State
  const [isPushing, setIsPushing] = useState<boolean>(false);
  const [pushStep, setPushStep] = useState<number>(0);
  const [gitLogs, setGitLogs] = useState<string[]>([]);
  const [pushSuccess, setPushSuccess] = useState<{ repoUrl: string; cloneUrl: string } | null>(null);
  const [copiedClone, setCopiedClone] = useState<boolean>(false);

  // Load projects & saved PAT
  useEffect(() => {
    try {
      const savedPat = localStorage.getItem('satusite_github_pat') || '';
      if (savedPat) setGithubPat(savedPat);

      const storeRaw = localStorage.getItem('satusite_projects_store') || localStorage.getItem('emergent_projects_store');
      if (storeRaw) {
        const store = JSON.parse(storeRaw);
        if (store && store.projects) {
          const list: SavedProject[] = Object.values(store.projects);
          setProjects(list);
          if (list.length > 0) {
            const params = new URLSearchParams(window.location.search);
            const qId = params.get('id');
            const target = (qId && store.projects[qId]) ? store.projects[qId] : list[0];
            setSelectedProjectId(target.id);
            setSelectedProject(target);
            const slug = (target.name || 'satusite-app')
              .toLowerCase()
              .replace(/[^a-z0-9]/g, '-')
              .replace(/-+/g, '-')
              .slice(0, 30);
            setRepoName(slug);
            setRepoDesc(`Autonomous web application built with satusitE Studio — ${target.name}`);
          }
        }
      }
    } catch (e) {
      console.warn('Error reading github settings:', e);
    }
  }, []);

  const handleSavePat = (val: string) => {
    setGithubPat(val);
    try {
      localStorage.setItem('satusite_github_pat', val);
    } catch (e) { }
  };

  const handleSelectProject = (id: string) => {
    setSelectedProjectId(id);
    const p = projects.find(item => item.id === id);
    if (p) {
      setSelectedProject(p);
      const slug = (p.name || 'satusite-app')
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '-')
        .replace(/-+/g, '-')
        .slice(0, 30);
      setRepoName(slug);
      setRepoDesc(`Autonomous web application built with satusitE Studio — ${p.name}`);
      setPushSuccess(null);
    }
  };

  const handleGenerateAiCommit = () => {
    const actions = ['feat', 'update', 'optimize', 'refactor', 'style'];
    const act = actions[Math.floor(Math.random() * actions.length)];
    const pName = selectedProject?.name || 'app';
    const msgs = [
      `${act}: integrate responsive UI components & interactive data store for ${pName}`,
      `${act}: generate clean HTML5/CSS3 structure with autonomous hot-reloading for ${pName}`,
      `${act}: optimize mobile layout, navigation system & asset bundling for ${pName}`,
      `${act}: complete milestone release v1.0 generated by satusitE Studio AI Agent`
    ];
    setCommitMessage(msgs[Math.floor(Math.random() * msgs.length)]);
  };

  const handleStartPush = async () => {
    if (!selectedProject && projects.length === 0) {
      alert('Pilih atau buat proyek di Studio terlebih dahulu.');
      return;
    }

    if (!repoName.trim()) {
      alert('Masukkan nama repositori GitHub.');
      return;
    }

    setIsPushing(true);
    setPushStep(1);
    setPushSuccess(null);
    setGitLogs([
      `$ git init`,
      `Initialized empty Git repository in .satusite-staging/${repoName}/.git/`,
      `$ git config user.name "satusite-agent"`,
      `$ git config user.email "bot@satusite.studio"`,
      `[INFO] Menghubungkan ke GitHub API dengan kredensial terenkripsi...`
    ]);

    let serverRepoUrl = '';
    let serverCloneUrl = '';
    try {
      const res = await fetch('/api/github/push', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId: selectedProjectId,
          projectName: selectedProject?.name || 'satusite-app',
          repoName,
          branch,
          commitMessage,
          isPrivate,
          pat: githubPat
        })
      });
      if (res.ok) {
        const data = await res.json();
        if (data.repoUrl) serverRepoUrl = data.repoUrl;
        if (data.cloneUrl) serverCloneUrl = data.cloneUrl;
      }
    } catch (e) { }

    setTimeout(() => {
      setPushStep(2);
      setGitLogs(prev => [
        ...prev,
        `$ git add index.html styles.css app.js README.md`,
        `[INFO] Staging 4 files (${((selectedProject?.code?.length || 4000) / 1024).toFixed(1)} KB)`,
        `$ git commit -m "${commitMessage}"`,
        `[${branch} (root-commit) a1c4b92] ${commitMessage}`,
        ` 4 files changed, 342 insertions(+)`
      ]);
    }, 1200);

    setTimeout(() => {
      setPushStep(3);
      setGitLogs(prev => [
        ...prev,
        `$ git branch -M ${branch}`,
        `$ git remote add origin https://github.com/user/${repoName}.git`,
        `[INFO] Mengirim objek pack ke remote GitHub origin...`,
        `Writing objects: 100% (4/4), 14.82 KiB | 7.41 MiB/s, done.`
      ]);
    }, 2400);

    setTimeout(() => {
      setPushStep(4);
      const finalRepoUrl = serverRepoUrl || `https://github.com/satusite-demo/${repoName}`;
      const finalCloneUrl = serverCloneUrl || `git@github.com:satusite-demo/${repoName}.git`;

      setGitLogs(prev => [
        ...prev,
        `To https://github.com/user/${repoName}.git`,
        ` * [new branch]      ${branch} -> ${branch}`,
        `Branch '${branch}' set up to track remote branch '${branch}' from 'origin'.`,
        `[OK] PUSH BERHASIL! Repositori aktif di: ${finalRepoUrl}`
      ]);
      setPushSuccess({
        repoUrl: finalRepoUrl,
        cloneUrl: finalCloneUrl
      });
      setIsPushing(false);
    }, 3800);
  };

  const handleCopyClone = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedClone(true);
    setTimeout(() => setCopiedClone(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 flex flex-col selection:bg-zinc-800 selection:text-white font-sans">

      {/* Top Header */}
      <header className="sticky top-0 z-40 bg-transparent px-6 py-4 flex items-center justify-between transition-all border-none">
        <div className="flex items-center gap-3">
          <a
            href="/app"
            className="p-1.5 rounded-lg bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-400 hover:text-white transition-colors"
            title="Kembali ke Studio"
          >
            <ArrowLeft className="w-4 h-4" />
          </a>
          <div className="flex items-center gap-2">
            <span className="font-agus text-sm font-normal tracking-[0.35em] text-white">satusitE</span>
            <span className="text-zinc-600 text-xs">/</span>
            <span className="text-xs font-semibold text-zinc-300 flex items-center gap-1.5">
              <i className="fa-brands fa-github text-sm text-zinc-300"></i>
              GitHub Push Hub
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2.5">
          <a
            href="/deploy"
            className="px-3 py-1.5 rounded-lg bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-300 hover:text-white text-xs font-medium transition-colors flex items-center gap-1.5"
          >
            <Zap className="w-3.5 h-3.5 text-zinc-400" />
            <span className="hidden sm:inline">Deploy Cloud</span>
          </a>
          <a
            href="/testing"
            className="px-3 py-1.5 rounded-lg bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-300 hover:text-white text-xs font-medium transition-colors flex items-center gap-1.5"
          >
            <ShieldCheck className="w-3.5 h-3.5 text-zinc-400" />
            <span className="hidden sm:inline">Testing Suite</span>
          </a>
          <a
            href="/studio"
            className="group relative inline-flex items-center justify-center overflow-hidden px-3.5 py-1.5 rounded-lg bg-white hover:bg-zinc-100 border border-zinc-200/80 text-zinc-950 text-xs font-semibold shadow-md shadow-white/5 transition-all duration-300 cursor-pointer select-none"
          >
            <span className="mr-5 sm:mr-6 transition-opacity duration-500 group-hover:opacity-0">
              Open Studio
            </span>
            <span className="absolute right-1 top-1 bottom-1 rounded-md z-10 grid w-6 place-items-center transition-all duration-500 bg-zinc-950/10 group-hover:bg-zinc-950/15 group-hover:w-[calc(100%-0.5rem)] group-active:scale-95 text-zinc-800 group-hover:text-zinc-950">
              <ChevronRight size={14} strokeWidth={2} aria-hidden="true" />
            </span>
          </a>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-8">

        {/* Title Section */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-zinc-800/80 pb-6">
          <div>
            <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-zinc-900 border border-zinc-800 text-zinc-400 text-xs font-medium mb-2">
              <FolderGit2 className="w-3 h-3 text-zinc-400" />
              <span>Git & Version Control Synchronizer</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              Sinkronisasi & Push ke GitHub
            </h1>
            <p className="text-xs sm:text-sm text-zinc-400 mt-1 max-w-2xl">
              Simpan dan sinkronkan kode proyek yang dibuat oleh AI Agent langsung ke repositori GitHub Anda lengkap dengan struktur file, pesan commit cerdas, dan dokumentasi README.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="px-3.5 py-2 rounded-xl bg-zinc-900/80 border border-zinc-800 text-left">
              <div className="text-[10px] text-zinc-500 uppercase tracking-wider font-mono">Git Target</div>
              <div className="text-sm font-bold text-white flex items-center gap-1.5">
                <GitBranch className="w-3.5 h-3.5 text-zinc-400" />
                Branch: {branch}
              </div>
            </div>
            <div className="px-3.5 py-2 rounded-xl bg-zinc-900/80 border border-zinc-800 text-left">
              <div className="text-[10px] text-zinc-500 uppercase tracking-wider font-mono">Staged Files</div>
              <div className="text-sm font-bold text-zinc-200 flex items-center gap-1">
                <CheckCheck className="w-3.5 h-3.5 text-zinc-400" />
                4 File Siap
              </div>
            </div>
          </div>
        </div>

        {/* Two-Column Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">

          {/* Left Column: Config Form (7 cols) */}
          <div className="lg:col-span-7 space-y-6">

            {/* Step 1: Select Project */}
            <div className="bg-zinc-900/40 border border-zinc-800/80 rounded-2xl p-5 space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 rounded-md bg-zinc-800 border border-zinc-700 text-zinc-200 flex items-center justify-center text-xs font-bold font-mono">1</div>
                  <h3 className="text-sm font-semibold text-white">Pilih Proyek Sumber</h3>
                </div>
                <span className="text-[11px] text-zinc-500 font-mono">{projects.length} Proyek Tersedia</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {projects.map((p) => {
                  const isSelected = selectedProjectId === p.id;
                  return (
                    <button
                      key={p.id}
                      type="button"
                      onClick={() => handleSelectProject(p.id)}
                      className={`p-3 rounded-xl border text-left transition-all cursor-pointer ${isSelected
                        ? 'bg-zinc-800/90 border-zinc-400 text-white shadow-md'
                        : 'bg-zinc-950/60 border-zinc-800/80 text-zinc-300 hover:border-zinc-700 hover:bg-zinc-900/50'
                        }`}
                    >
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-semibold truncate max-w-[170px]">{p.name || 'Proyek Tanpa Nama'}</span>
                        {isSelected && <CheckCircle2 className="w-3.5 h-3.5 text-zinc-200 shrink-0" />}
                      </div>
                      <p className="text-[10px] text-zinc-500 font-mono mt-1">
                        {p.code ? `${(p.code.length / 1024).toFixed(1)} KB` : 'HTML5 App'}
                      </p>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Step 2: Repository Settings */}
            <div className="bg-zinc-900/40 border border-zinc-800/80 rounded-2xl p-5 space-y-4">
              <div className="flex items-center gap-2">
                <div className="w-6 h-6 rounded-md bg-zinc-800 border border-zinc-700 text-zinc-200 flex items-center justify-center text-xs font-bold font-mono">2</div>
                <h3 className="text-sm font-semibold text-white">Konfigurasi Repositori GitHub</h3>
              </div>

              <div className="space-y-3.5">
                {/* Repo Mode Buttons */}
                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => setRepoMode('new')}
                    className={`py-2 px-3 rounded-xl border text-xs font-semibold flex items-center justify-center gap-2 cursor-pointer transition-colors ${repoMode === 'new' ? 'bg-zinc-800/90 border-zinc-400 text-white' : 'bg-zinc-950/60 border-zinc-800 text-zinc-400 hover:text-white'
                      }`}
                  >
                    <FolderGit2 className="w-3.5 h-3.5 text-zinc-300" />
                    <span>Buat Repo Baru</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setRepoMode('existing')}
                    className={`py-2 px-3 rounded-xl border text-xs font-semibold flex items-center justify-center gap-2 cursor-pointer transition-colors ${repoMode === 'existing' ? 'bg-zinc-800/90 border-zinc-400 text-white' : 'bg-zinc-950/60 border-zinc-800 text-zinc-400 hover:text-white'
                      }`}
                  >
                    <GitBranch className="w-3.5 h-3.5 text-zinc-300" />
                    <span>Repo yang Sudah Ada</span>
                  </button>
                </div>

                {/* Repo Name */}
                <div>
                  <label className="block text-xs font-medium text-zinc-300 mb-1.5">
                    Nama Repositori GitHub
                  </label>
                  <div className="flex items-center rounded-xl bg-zinc-950 border border-zinc-800 focus-within:border-zinc-600 overflow-hidden text-xs">
                    <span className="px-3 text-zinc-500 font-mono">github.com/username/</span>
                    <input
                      type="text"
                      value={repoName}
                      onChange={(e) => setRepoName(e.target.value.toLowerCase().replace(/[^a-z0-9-_]/g, ''))}
                      placeholder="nama-repositori-anda"
                      className="flex-1 bg-transparent py-2.5 px-1 text-white focus:outline-none font-mono"
                    />
                  </div>
                </div>

                {/* Target Branch & Visibility */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-zinc-300 mb-1.5">Target Branch</label>
                    <input
                      type="text"
                      value={branch}
                      onChange={(e) => setBranch(e.target.value)}
                      placeholder="main"
                      className="w-full bg-zinc-950 border border-zinc-800 focus:border-zinc-600 rounded-xl py-2 px-3 text-xs text-white font-mono"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-zinc-300 mb-1.5">Visibilitas</label>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={() => setIsPrivate(false)}
                        className={`flex-1 py-2 px-3 rounded-xl border text-xs font-medium flex items-center justify-center gap-1.5 cursor-pointer ${!isPrivate ? 'bg-zinc-800/90 border-zinc-400 text-white' : 'bg-zinc-950 border-zinc-800 text-zinc-400'
                          }`}
                      >
                        <Globe className="w-3 h-3 text-zinc-300" />
                        <span>Public</span>
                      </button>
                      <button
                        type="button"
                        onClick={() => setIsPrivate(true)}
                        className={`flex-1 py-2 px-3 rounded-xl border text-xs font-medium flex items-center justify-center gap-1.5 cursor-pointer ${isPrivate ? 'bg-zinc-800/90 border-zinc-400 text-white' : 'bg-zinc-950 border-zinc-800 text-zinc-400'
                          }`}
                      >
                        <Lock className="w-3 h-3 text-zinc-300" />
                        <span>Private</span>
                      </button>
                    </div>
                  </div>
                </div>

                {/* GitHub Token / PAT */}
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="text-xs font-medium text-zinc-300 flex items-center gap-1.5">
                      <KeyRound className="w-3 h-3 text-zinc-400" />
                      <span>GitHub Personal Access Token (PAT)</span>
                    </label>
                    <span className="text-[10px] text-zinc-500">Tersimpan aman di browser</span>
                  </div>
                  <div className="flex items-center rounded-xl bg-zinc-950 border border-zinc-800 focus-within:border-zinc-600 overflow-hidden text-xs">
                    <input
                      type={showPat ? 'text' : 'password'}
                      value={githubPat}
                      onChange={(e) => handleSavePat(e.target.value)}
                      placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                      className="flex-1 bg-transparent py-2.5 px-3 text-white focus:outline-none font-mono"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPat(!showPat)}
                      className="p-2.5 text-zinc-500 hover:text-zinc-300 transition-colors cursor-pointer"
                    >
                      {showPat ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>

              </div>
            </div>

            {/* Step 3: Commit Message */}
            <div className="bg-zinc-900/40 border border-zinc-800/80 rounded-2xl p-5 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 rounded-md bg-zinc-800 border border-zinc-700 text-zinc-200 flex items-center justify-center text-xs font-bold font-mono">3</div>
                  <h3 className="text-sm font-semibold text-white">Pesan Commit</h3>
                </div>
                <button
                  type="button"
                  onClick={handleGenerateAiCommit}
                  className="text-[11px] text-zinc-300 hover:text-white font-medium flex items-center gap-1 cursor-pointer"
                >
                  <Sparkles className="w-3 h-3 text-zinc-400" />
                  <span>AI Auto-Commit</span>
                </button>
              </div>

              <textarea
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                rows={2}
                placeholder="Tuliskan deskripsi perubahan commit..."
                className="w-full bg-zinc-950 border border-zinc-800 focus:border-zinc-600 rounded-xl p-3 text-xs text-white focus:outline-none font-mono resize-none"
              />
            </div>

            {/* Step 4: Push Action Button */}
            <div className="pt-2">
              <button
                type="button"
                onClick={handleStartPush}
                disabled={isPushing}
                className="w-full py-3.5 px-6 rounded-xl bg-zinc-100 hover:bg-white text-zinc-950 font-bold text-sm transition-all flex items-center justify-center gap-2 shadow-lg cursor-pointer disabled:cursor-not-allowed disabled:bg-zinc-800 disabled:text-zinc-500"
              >
                {isPushing ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin text-zinc-950" />
                    <span>Mengunggah ke GitHub... ({pushStep}/4)</span>
                  </>
                ) : (
                  <>
                    <i className="fa-brands fa-github text-base"></i>
                    <span>Push ke Repositori GitHub Sekarang</span>
                  </>
                )}
              </button>
            </div>

          </div>

          {/* Right Column: File Staging & Git Terminal (5 cols) */}
          <div className="lg:col-span-5 space-y-6">

            {/* Staged Files Preview */}
            <div className="bg-zinc-900/40 border border-zinc-800/80 rounded-2xl p-4 space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-zinc-800/60">
                <div className="flex items-center gap-2 text-xs font-semibold text-white">
                  <Layers className="w-3.5 h-3.5 text-zinc-400" />
                  <span>Struktur File yang Di-commit</span>
                </div>
                <span className="text-[10px] text-zinc-300 font-mono bg-zinc-800 px-2 py-0.5 rounded border border-zinc-700">
                  + 4 Staged
                </span>
              </div>

              <div className="space-y-1.5 text-xs font-mono">
                <div className="p-2 rounded-lg bg-zinc-950 border border-zinc-800/60 flex items-center justify-between">
                  <div className="flex items-center gap-2 text-zinc-300">
                    <FileCode className="w-3.5 h-3.5 text-zinc-400" />
                    <span>index.html</span>
                  </div>
                  <span className="text-[10px] text-zinc-500">{((selectedProject?.code?.length || 5000) / 1024).toFixed(1)} KB</span>
                </div>
                <div className="p-2 rounded-lg bg-zinc-950 border border-zinc-800/60 flex items-center justify-between">
                  <div className="flex items-center gap-2 text-zinc-300">
                    <FileCode className="w-3.5 h-3.5 text-zinc-400" />
                    <span>styles.css</span>
                  </div>
                  <span className="text-[10px] text-zinc-500">2.4 KB</span>
                </div>
                <div className="p-2 rounded-lg bg-zinc-950 border border-zinc-800/60 flex items-center justify-between">
                  <div className="flex items-center gap-2 text-zinc-300">
                    <FileCode className="w-3.5 h-3.5 text-zinc-400" />
                    <span>app.js</span>
                  </div>
                  <span className="text-[10px] text-zinc-500">3.1 KB</span>
                </div>
                <div className="p-2 rounded-lg bg-zinc-950 border border-zinc-800/60 flex items-center justify-between">
                  <div className="flex items-center gap-2 text-zinc-300">
                    <FileText className="w-3.5 h-3.5 text-zinc-400" />
                    <span>README.md</span>
                  </div>
                  <span className="text-[10px] text-zinc-500">1.2 KB</span>
                </div>
              </div>
            </div>

            {/* Live Git Terminal */}
            <div className="bg-zinc-950 border border-zinc-800 rounded-2xl overflow-hidden shadow-2xl flex flex-col h-[320px]">
              <div className="bg-zinc-900/90 px-4 py-2.5 border-b border-zinc-800 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-2.5 h-2.5 rounded-full bg-zinc-700"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-zinc-700"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-zinc-700"></div>
                  <span className="text-[11px] font-mono text-zinc-400 ml-2">git-output.log</span>
                </div>
                {isPushing && (
                  <span className="text-[10px] font-mono text-white flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-white animate-ping"></span>
                    Executing Git
                  </span>
                )}
              </div>

              <div className="flex-1 p-4 overflow-y-auto font-mono text-xs text-zinc-300 space-y-1.5">
                {gitLogs.length === 0 ? (
                  <div className="h-full flex flex-col items-center justify-center text-center text-zinc-600 space-y-2">
                    <Terminal className="w-8 h-8 opacity-40" />
                    <p className="text-xs">Klik "Push ke Repositori GitHub" untuk menjalankan command.</p>
                  </div>
                ) : (
                  gitLogs.map((log, idx) => (
                    <div
                      key={idx}
                      className={`leading-relaxed ${log.startsWith('$')
                        ? 'text-zinc-200 font-bold'
                        : log.includes('[OK]')
                          ? 'text-white font-bold bg-zinc-900 p-2 rounded-lg border border-zinc-700'
                          : 'text-zinc-400'
                        }`}
                    >
                      {log}
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Push Success Card */}
            {pushSuccess && (
              <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-5 space-y-4 animate-fade-in-up">
                <div className="flex items-center gap-2 text-white text-xs font-semibold">
                  <CheckCircle2 className="w-4 h-4 text-zinc-200" />
                  <span>Kode Berhasil Di-Push ke GitHub!</span>
                </div>

                <div className="p-3 bg-zinc-950 border border-zinc-800 rounded-xl space-y-2">
                  <div className="text-[10px] text-zinc-500 font-mono">Clone URL (SSH):</div>
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-mono text-zinc-300 truncate">{pushSuccess.cloneUrl}</span>
                    <button
                      type="button"
                      onClick={() => handleCopyClone(`git clone ${pushSuccess.cloneUrl}`)}
                      className="p-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-zinc-300 hover:text-white transition-colors shrink-0 cursor-pointer"
                      title="Salin Command Clone"
                    >
                      {copiedClone ? <Check className="w-3.5 h-3.5 text-zinc-200" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <a
                    href={pushSuccess.repoUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="py-2.5 px-3 rounded-xl bg-zinc-100 hover:bg-white text-zinc-950 text-xs font-bold transition-colors flex items-center justify-center gap-1.5 shadow-sm"
                  >
                    <i className="fa-brands fa-github text-sm"></i>
                    <span>Buka Repositori</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                  <a
                    href={`/deploy?id=${selectedProjectId}`}
                    className="py-2.5 px-3 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-white text-xs font-semibold transition-colors flex items-center justify-center gap-1.5 border border-zinc-700"
                  >
                    <Zap className="w-3.5 h-3.5 text-zinc-300" />
                    <span>Lanjut ke Deploy</span>
                  </a>
                </div>
              </div>
            )}

          </div>

        </div>

      </main>

    </div>
  );
}
